apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: busybox
  name: busybox
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - image: alpine
        name: busybox
        command:
        - /bin/sh
        - -c
        - "apk update && apk add curl; while true; do curl http://httpd; done"